-- 集合查询

-- UNOIN，会自动去掉两个集合中的重复的元素
SELECT * FROM STUDENTS WHERE SDEPT = "CS" UNOIN SELECT * FROM STUDENTS WHERE SAGE <= 19;

-- UNION ALL,对两个集合中的元祖取并集，并且保留重复的元素
SELECT * FROM STUDENTS WHERE SDEPT = "CS" UNOIN ALL SELECT * FROM STUDENTS WHERE SAGE <= 19;



-- INTERSECT,求交集
SELECT * FROM STUDENTS WHERE SDEPT = "CS" INTERSECT SELECT * FROM STUDENTS WHERE SAGE <= 19;
-- 相当于 
SELECT * FROM STUDENTS WHERE SDEPT =  "CS" AND SAGE <=19;


-- EXCEPT,求两个集合的差集
SELECT * FROM STUDENTS WHERE SDEPT="CS" EXCEPT SELECT * FROM STUDENTS WHERE sAGE <=19;
-- 上面的查询相当于下面的语句：
SELECT * FROM STUDENTS WHERE SDEPT = "CS" AND SAGE >19;
