-- 视图

CREATE VIEW <视图名>[<列名>,<列名>...] AS <子查询>[WITH CHECK OPTION];
-- 这里省略了视图IS_STUDENT的列名，隐含了由子查询中SELECT子句中的三个列名组成。
CREATE VIEW IS_STUDENT AS SELECT SNO,SANEM,SAGE FROM STUDENTS WHERE SDEPT = "IS";
CREATE VIEW IS_STUDENT AS SELECT SNO,SANEM,SAGE FROM STUDENTS WHERE SDEPT = "IS" WITH CHECK OPTION;
